[[redirects]]
  from = "https://www.rivaan.co/*"
  to = "https://rivaan.co/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet, noimageindex"
